name: gym_app
description: "Multi-Gym Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  google_fonts: ^8.0.1
  fl_chart: ^1.1.1
  shimmer: ^3.0.0
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  camera: ^0.11.3+1
  google_mlkit_face_detection: ^0.13.2
  tflite_flutter: ^0.12.1
  image: ^4.7.2
  flutter_image_compress: ^2.4.0
  supabase_flutter: ^2.12.0
  image_picker: ^1.2.1
  image_cropper: ^11.0.0
  table_calendar: ^3.1.2
  flutter_riverpod: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.31.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/models/mobile_face_net.tflite

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#DC2626"   # AppColors.primary (rojo GymPro)
  image: "assets/icon.png"
  color_dark: "#0F172A" # AppColors.backgroundDark
  image_dark: "assets/icon.png"
  android: true
  ios: true
