name: gym_app
description: "Multi-Gym Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.31.0
  sqlite3_flutter_libs: ^0.6.0+eol
  path_provider: ^2.1.5
  path: ^1.9.1
  http: ^1.6.0
  flutter_secure_storage: ^10.0.0
  google_fonts: ^6.2.1
  fl_chart: ^0.71.0
  shimmer: ^3.0.0
  intl: ^0.20.1
  cached_network_image: ^3.4.1
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
